name: todo
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.4
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.6
  kf_drawer: ^1.2.0
  introduction_screen: ^2.1.0
  flutter_spinkit: ^5.1.0
  rounded_loading_button: ^2.0.5
  font_awesome_flutter: ^9.1.0
  flutter_advanced_drawer: ^1.2.3
  flutter_slidable: ^0.6.0
  circular_check_box: ^1.0.4
  ms_undraw: ^3.0.1+1
  url_launcher: ^6.0.10
  change_app_package_name: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/images/